export const TrelloConstants = {
  ADD_CARD: 'ADD_CARD',
  DELETE_CARD: 'DELETE_CARD',
  ADD_LIST: 'ADD_LIST',
  DELETE_LIST: 'DELETE_LIST',
  MOVE_CARD: 'MOVE_CARD',
  SORT_BY_CREATION_TIME: 'SORT_BY_CREATION_TIME',
  SORT_BY_REV_CREATION_TIME: 'SORT_BY_REV_CREATION_TIME',
};
